"""Entitlement evaluation and enforcement models.

The entitlement rule comes from the fixture, never from here (DEC-012): systems combine tenant,
roles and direct grants differently, and a hardcoded predicate is not merely incomplete against
others -- its wrongness surfaces as confident findings that the index disagrees with the source,
generated by misunderstanding what the source meant.

Enforcement models are a closed set (DEC-013). A fixture able to describe enforcement freely could
prove anything, since the author would write both the bug and the expectation.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence

from tearline.domain import Entitlement, EntitlementState, Principal

Enforcement = Callable[[Entitlement, Principal], bool]


def _tenant_ok(ent: Entitlement, principal: Principal, *, empty_is_unrestricted: bool) -> bool:
    if not ent.tenants:
        return empty_is_unrestricted
    return principal.tenant in ent.tenants


def _role_ok(ent: Entitlement, principal: Principal, *, empty_is_unrestricted: bool) -> bool:
    if not ent.roles:
        return empty_is_unrestricted
    if "everyone" in ent.roles or ent.roles & principal.roles:
        return True
    return principal.id in ent.principals


def entitled_by_rule(ent: Entitlement, principal: Principal) -> bool:
    """tenant AND (role OR direct). An `unknown` entitlement grants nothing (DEC-003)."""
    if ent.state is not EntitlementState.STATED:
        return False
    return _tenant_ok(ent, principal, empty_is_unrestricted=False) and _role_ok(
        ent, principal, empty_is_unrestricted=False
    )


def admitted_by_naive_filter(ent: Entitlement, principal: Principal) -> bool:
    """Admit unless a stated restriction excludes the principal.

    The bug DEC-003 names. `state` is never consulted -- the filter only asks whether something
    excludes, so a chunk carrying no tenant and no role is admitted to everyone.
    """
    return _tenant_ok(ent, principal, empty_is_unrestricted=True) and _role_ok(
        ent, principal, empty_is_unrestricted=True
    )


ENFORCEMENT_MODELS: dict[str, Enforcement] = {
    "rule": entitled_by_rule,
    "naive-tenant-exclusion": admitted_by_naive_filter,
}


def safe_bound(entitlements: Sequence[Entitlement]) -> Entitlement | None:
    """A chunk contains material from all its sources, so a principal may see it only if entitled
    by all of them (DEC-015). `None` when there are no sources -- untraceable, not unrestricted."""
    if not entitlements:
        return None
    bound = entitlements[0]
    for other in entitlements[1:]:
        bound = bound.intersect(other)
    return bound


def entitled_by_all(entitlements: Sequence[Entitlement], principal: Principal) -> bool:
    return bool(entitlements) and all(entitled_by_rule(e, principal) for e in entitlements)
