"""Enforcement models, and combining several sources' entitlements.

The entitlement rule itself is not here: it comes from the fixture (DEC-012, `entitlement_rule.py`).
Systems combine tenant, roles and direct grants differently, and a hardcoded predicate is not merely
incomplete against others -- its wrongness surfaces as confident findings that the index disagrees
with the source, generated by misunderstanding what the source meant.

Enforcement models are a closed set (DEC-013). A fixture able to describe enforcement freely could
prove anything, since the author would write both the bug and the expectation. Each is a *reading*
of the stated rule rather than a predicate of its own, so a scenario against a system with different
semantics gets a naive filter that is naive about that system.
"""

from __future__ import annotations

from collections.abc import Callable, Sequence

from tearline.domain import Entitlement, Principal
from tearline.entitlement_rule import EntitlementRule

Enforcement = Callable[[Entitlement, Principal], bool]


def enforcement_for(rule: EntitlementRule, model: str) -> Enforcement:
    """The predicate a variant's declared enforcement model applies, read from `rule`."""
    match model:
        case "rule":
            return rule.entitled
        case "naive-tenant-exclusion":
            return rule.admitted_by_naive_filter
    raise ValueError(f"unknown enforcement model {model!r}; DEC-013 closes the set")


#: The closed set, for validation and for error messages. The values are built per scenario by
#: `enforcement_for`, because a model is a reading of a stated rule and not a standalone predicate.
ENFORCEMENT_MODELS = frozenset({"rule", "naive-tenant-exclusion"})


def safe_bound(entitlements: Sequence[Entitlement]) -> Entitlement | None:
    """A chunk contains material from all its sources, so a principal may see it only if entitled
    by all of them (DEC-015). `None` when there are no sources -- untraceable, not unrestricted."""
    if not entitlements:
        return None
    bound = entitlements[0]
    for other in entitlements[1:]:
        bound = bound.intersect(other)
    return bound


def entitled_by_all(
    rule: EntitlementRule, entitlements: Sequence[Entitlement], principal: Principal
) -> bool:
    return bool(entitlements) and all(rule.entitled(e, principal) for e in entitlements)
